	<div class="header">
	<style type="text/css">
		*{
			padding: 5px;
		}
		.tc{
			margin-left: auto;
  			margin-right: auto;
		}
		.tth{
			width: 40%;
			height: 25px;
		}
		.heading{
			font-size: 25px;
			font: bold;
		}
		.w{
			color: white;
		}
		.content{
			border: 1px solid gray;
			height: auto;
			min-height: 535px;
			padding-bottom: 20px;
			background-color: #EBECF0;
		}
		.menu{
			height: 50px;
			font-size: 18px;
			background-color: #808080;
		}
		.th{
			width: 14%;
		}
		.header{
			border: 1px solid gray;
		}
		.footer{
			border: 1px solid gray;
			height: 50px;
			text-align: center;
			font-size: 20px;
			background-color: #808080;
			color: white;
		}
	</style>

	<table border="0" width="100%" class="menu">
		<tr>
			<th class="th"><a href="index.php?c=product&a=grid" class="w">Product</a></th>
			<th class="th"><a href="index.php?c=category&a=grid" class="w">Category</a></th>
			<th class="th"><a href="index.php?c=customer&a=grid" class="w">Customer</a></th>
			<th class="th"><a href="index.php?c=vendor&a=grid" class="w">Vendor</a></th>
			<th class="th"><a href="index.php?c=salesman&a=grid" class="w">Salesman</a></th>
			<th class="th"><a href="index.php?c=ShippingMethod&a=grid" class="w">Shipping method</a></th>
			<th class="th"><a href="index.php?c=PaymentMethod&a=grid" class="w">Payment method</a></th>
		</tr>
	</table>
</div>
	