<!--ADD PRODUCT-->
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Add Product</title>
</head>
<body>
<form action="index.php?c=product&a=insert" method="post">
<?php require_once 'View\html\header.phtml'; ?>

<div class="content">
	<table class="tc">
		<tr>
			<td class="heading"> ADD PRODUCT</td>
			<td>
				<a href="index.php?c=product&a=grid">Cancel </a>
			</td>
			<td>
				<input type="submit" name="button" value="ADD">
			</td>
		</tr>
	</table>
	<br>
	<table border="1" cellspacing="0"  class="tc">
		<tr>
			<th colspan="2"><strong>Product Information</strong></th>
		</tr>
		<tr>
			<td class="tth">NAME</td>
			<td>
				<input type="text" name="product[name]" placeholder="name">
			</td>
		</tr>
		<tr>
			<td class="tth">SKU</td>
			<td>
				<input type="text" name="product[sku]" placeholder="SKU">
			</td>
		</tr>
		<tr>
			<td class="tth">COST</td>
			<td>
				<input type="text" name="product[cost]" placeholder="cost">
			</td>
		</tr>
		<tr>
			<td class="tth">PRICE</td>
			<td>
				<input type="text" name="product[price]" placeholder="price">
			</td>
		</tr>
		<tr>
			<td class="tth">QUANTITY</td>
			<td>
				<input type="text" name="product[quantity]" placeholder="Quantity">
			</td>
		</tr>
		<tr>
			<td class="tth">DESCRIPTION</td>
			<td>
				<textarea id="ta" name="product[description]" rows="3" cols="40" placeholder="Description"></textarea>
			</td>
		</tr>
		<tr>
			<td class="tth">STATUS</td>
			<td>
				<select name="product[status]">
					<option>-Choose an Option-</option>
					<option value="1">Active</option>
					<option value="0">Inactive</option>
				</select>
			</td>
		</tr>
		<tr>
			<td class="tth">COLOR</td>
			<td>
				<select class="center2" name="product[color]">
					<option>-Choose Color-</option>
					<option value="red">Red</option>
					<option value="green">Green</option>
					<option value="blue">Blue</option>
					<option value="yellow">Yellow</option>
				</select>
			</td>
		</tr>
		<tr>
			<td class="tth">MATERIAL</td>
			<td>
				<select name="product[material]">
					<option>-Select Material-</option>
					<option value="material 1">Material 1</option>
					<option value="material 2">Material 2</option>
					<option value="material 3">Material 3</option>
					<option value="material 4">Material 4</option>
				</select>
			</td>
		</tr>
	</table>
</div>
<?php require_once 'C:\xampp\htdocs\cybercom\Project\View\html\footer.phtml'; ?>
</form>
</body>