<!--ADD PRODUCT-->
<?php 
require_once 'C:\xampp\htdocs\cybercom\Project\Model\Core\Model_Adapter.php';

$id = $_GET['id'];

$sql = "SELECT * FROM `product` WHERE `product_id`= $id";
$result = new Model_adapter();
$data = $result->fetchRow($sql);

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Product</title>
</head>
<body>
<?php require_once 'C:\xampp\htdocs\cybercom\Project\View\html\header.phtml'; ?>

	<div class="content">
	<br>
	<form action="index.php?c=product&a=update&id=<?php echo $_GET['id']; ?>" method="post">
	<?php $id = $_GET['id']; ?>
	<table class="tc">
		<tr>
			<td class="heading">EDIT PRODUCT</td>
			<td>
				<a href="index.php?c=product&a=grid">Cancel </a>
			</td>
			<td>
				<input type="submit" name="button" value="update">
			</td>
		</tr>
	</table>
	<br>
	<table border="1" cellspacing="0"  class="tc">
		<tr>
			<th colspan="2"><strong>Product Information</strong></th>
		</tr>
		<tr>
			<td class="tth">NAME</td>
			<td>
				<input type="text" name="product[name]" placeholder="name" value="<?php echo $data['name']; ?>">
			</td>
		</tr>
		<tr>
			<td class="tth">SKU</td>
			<td>
				<input type="text" name="product[sku]" placeholder="SKU" value="<?php echo $data['sku']; ?>">
			</td>
		</tr>
		<tr>
			<td class="tth">COST</td>
			<td>
				<input type="text" name="product[cost]" placeholder="cost" value="<?php echo $data['cost']; ?>">
			</td>
		</tr>
		<tr>
			<td class="tth">PRICE</td>
			<td>
				<input type="text" name="product[price]" placeholder="price" value="<?php echo $data['price']; ?>">
			</td>
		</tr>
		<tr>
			<td class="tth">QUANTITY</td>
			<td>
				<input type="text" name="product[quantity]" placeholder="Quantity" value="<?php echo $data['quantity']; ?>">
			</td>
		</tr>
		<tr>
			<td class="tth">DESCRIPTION</td>
			<td>
				<textarea id="ta" name="product[description]" rows="3" cols="40" placeholder="Description"><?php echo $data['description']; ?></textarea>
			</td>
		</tr>
		<tr>
			<td class="tth">STATUS</td>
			<td>
				<select name="product[status]">
					<option>-Choose an Option-</option>
					<option value="active"<?php if ($data['status'] == "active") { echo "selected";	} ;?>>Active</option>
					<option value="inactive"<?php if ($data['status'] == "inactive") { echo "selected";	} ;?>>Inactive</option>
				</select>
			</td>
		</tr>
		<tr>
			<td class="tth">COLOR</td>
			<td>
				<select class="center2" name="product[color]">
					<option>-Choose Color-</option>
					<option value="red"<?php if ($data['color'] == "red") { echo "selected"; } ;?>>Red</option>
					<option value="green"<?php if ($data['color'] == "green") { echo "selected"; } ;?>>Green</option>
					<option value="blue"<?php if ($data['color'] == "blue") { echo "selected"; } ;?>>Blue</option>
					<option value="yellow"<?php if ($data['color'] == "yellow") { echo "selected"; } ;?>>Yellow</option>
				</select>
			</td>
		</tr>
		<tr>
			<td class="tth">MATERIAL</td>
			<td>
				<select name="product[material]">
					<option>-Select Material-</option>
					<option value="material 1"<?php if ($data['material'] == "material 1") { echo "selected"; } ;?>>Material 1</option>
					<option value="material 2"<?php if ($data['material'] == "material 2") { echo "selected"; } ;?>>Material 2</option>
					<option value="material 3"<?php if ($data['material'] == "material 3") { echo "selected"; } ;?>>Material 3</option>
					<option value="material 4"<?php if ($data['material'] == "material 4") { echo "selected"; } ;?>>Material 4</option>
				</select>
			</td>
		</tr>
	</table>
	</form>
</div>
<?php require_once 'C:\xampp\htdocs\cybercom\Project\View\html\footer.phtml'; ?>
</body>
</html>