<?php 
require_once 'C:\xampp\htdocs\cybercom\Project\Model\Core\Model_Adapter.php';

$result = new Model_adapter();
$sql = "SELECT * FROM product";
$products = $result->fetchAll($sql);

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<form action="index.php?c=product&a=add" method="post">
<?php require_once 'View\html\header.phtml'; ?>

<div class="content">
	<table class="tc" width="100%">
		<tr>
			<td class="heading" style="text-align: left;"> MANAGE PRODUCTS</td>
			<td style="text-align: right;">
				<input type="submit" name="add" value="Add Product">
			</td>
		</tr>
	</table>
	<br>
	<table border="1" cellspacing="0" class="tc">
		<tr style="height: 30px; font-size: 18px;">
			<th>Product Id</th>
			<th>Name</th>
			<th>SKU</th>
			<th>Cost</th>
			<th>Price</th>
			<th>Quantity</th>
			<th>Description</th>
			<th>Status</th>
			<th>Color</th>
			<th>Material</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>Media</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($products as $product): ?>
		<tr>
			<td><?php echo $product['product_id']; ?></td>
			<td><?php echo $product['name']; ?></td>
			<td><?php echo $product['sku']; ?></td>
			<td><?php echo $product['cost']; ?></td>
			<td><?php echo $product['price']; ?></td>
			<td><?php echo $product['quantity']; ?></td>
			<td><?php echo $product['description']; ?></td>
			<td><?php echo $product['status']; ?></td>
			<td><?php echo $product['color']; ?></td>
			<td><?php echo $product['material']; ?></td>
			<td><?php echo $product['created_at']; ?></td>
			<td><?php echo $product['updated_at']; ?></td>
			<td><a href="index.php?c=product_media&a=media&id=<?php echo $product['product_id']; ?>">view</td>
			<td><a href="index.php?c=product&a=edit&id=<?php echo $product['product_id']; ?>">Edit</td>
			<td><a href="index.php?c=product&a=delete&id=<?php echo $product['product_id']; ?>">Delete</td>
		</tr>
		<?php endforeach; ?>
		
	</table>
</div>
<?php require_once 'View\html\footer.phtml'; ?>
</form>
</body>
</html>