<!--ADD PRODUCT-->
<?php 
require_once 'Model\Core\Model_Adapter.php';

$id = $_GET['id'];
$sql= "SELECT * FROM `salesman` WHERE `salesman_id`= $id";
$result = new Model_Adapter();
$data = $result->fetchRow($sql);

$sql= "SELECT * FROM `salesman_address` WHERE `salesman_id`= $id";
$data1 = $result->fetchRow($sql);
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Salesman</title>
</head>
<body>
<form action="index.php?c=salesman&a=update&id=<?php echo $_GET['id']; ?>" method="post">
<?php require_once 'View\html\header.phtml' ?>
<div class="content" style="height: 720px;">
<br>
<table class="tc">
	<tr>
		<td class="heading">Edit Salesman</td>
		<td>
			<a href="index.php?c=salesman&a=grid">Cancel </a>
		</td>
		<td>
			<input type="submit" name="button" value="update">
		</td>
	</tr>
</table>
<br>
<table border="1" cellspacing="0"  class="tc">
	<tr>
		<th colspan="2"><strong>Salesman Information</strong></th>
	</tr>
	<tr>
		<td class="tth">First_name</td>
		<td>
			<input type="text" name="salesman[first_name]" placeholder="First_name" value="<?php echo $data['first_name']; ?>">
		</td>
	</tr>
	<tr>
		<td class="tth">Last_name</td>
		<td>
			<input type="text" name="salesman[last_name]" placeholder="Last_name" value="<?php echo $data['last_name']; ?>">
		</td>
	</tr>
	<tr>
		<td class="tth">Email</td>
		<td>
			<input type="text" name="salesman[email]" placeholder="email" value="<?php echo $data['email']; ?>">
		</td>
	</tr>
	<tr>
		<td class="tth">Mobile</td>
		<td>
			<input type="number" name="salesman[mobile]" placeholder="mobile no" value="<?php echo $data['mobile']; ?>">
		</td>
	</tr>
	<tr>
		<td class="tth">Gender</td>
		<td>
			<input type="radio" name="salesman[gender]" value="male"<?php if ($data['gender'] == "male") {
				echo "checked";	} ;?>>Male
			<input type="radio" name="salesman[gender]" value="female"<?php if ($data['gender'] == "female") {
				echo "checked";	} ;?>>Female
		</td>
	</tr>
	<tr>
		<td class="tth">Status</td>
		<td>
			<select name="salesman[status]">
				<option>-Choose an Option-</option>
				<option value="active"<?php if ($data['status'] == "active") { echo "selected";	} ;?>>Active</option>
				<option value="inactive"<?php if ($data['status'] == "inactive") { echo "selected";	} ;?>>Inactive</option>
			</select>
		</td>
	</tr>
	<tr>
		<td class="tth">Company</td>
		<td>
			<input type="text" name="salesman[company]" placeholder="Company" value="<?php echo $data['company']; ?>">
		</td>
	</tr>
</table>
<br>
<center>
<strong>Address</strong>
</center>
<table border="1" cellspacing="0"  class="tc">
	<tr>
		<td class="tth">Address</td>
		<td>
			<textarea name="salesman[address]" rows="3" cols="40" placeholder="Address"><?php echo $data1['address']; ?></textarea>
		</td>
	</tr>
	<tr>
		<td class="tth">City</td>
		<td>
			<input type="text" name="salesman[city]" placeholder="City" value="<?php echo $data1['city']; ?>">
		</td>
	</tr>
	<tr>
		<td class="tth">State</td>
		<td>
			<input type="text" name="salesman[state]" placeholder="State" value="<?php echo $data1['state']; ?>">
		</td>
	</tr>
	<tr>
		<td class="tth">Country</td>
		<td>
			<input type="text" name="salesman[country]" placeholder="Country" value="<?php echo $data1['country']; ?>">
		</td>
	</tr>
	<tr>
		<td class="tth">Zipcode</td>
		<td>
			<input type="number" name="salesman[zipcode]" placeholder="Zipcode" value="<?php echo $data1['zipcode']; ?>">
		</td>
	</tr>
</table>
</div>
<?php require_once 'View\html\footer.phtml' ?>
</form>
</body>
</html>