<?php 
require_once 'Model\Core\Model_Adapter.php';

$result = new Model_Adapter();
// $sql = "SELECT * FROM Salesman";
$sql = "SELECT * FROM salesman s INNER JOIN salesman_address sa ON s.salesman_id = sa.salesman_id;";
$datas = $result->fetchAll($sql);

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<form action="index.php?c=salesman&a=add" method="post">
<?php require_once 'View\html\header.phtml' ?>
<div class="content">
<table class="tc" width="100%">
	<tr>
		<td class="heading" style="text-align: left;"> Salesmans</td>
		<td style="text-align: right;">
			<input type="submit" name="add" value="Add Salesman">
		</td>
	</tr>
</table>	
<br>
<table border="1" cellspacing="0" class="tc">
	<tr style="height: 30px; font-size: 18px;">
		<th>Salesman ID</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
		<th>Mobile</th>
		<th>Gender</th>
		<th>Status</th>
		<th>Company</th>		
		<th>Country</th>	
		<th>Created At</th>			
		<th>Updated At</th>			
		<th>Prices</th>	
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>

	<?php foreach ($datas as $salesman): ?>

	<tr class="center">
			<td><?php echo $salesman['salesman_id']; ?></td>
			<td><?php echo $salesman['first_name']; ?></td>
			<td><?php echo $salesman['last_name']; ?></td>
			<td><?php echo $salesman['email']; ?></td>
			<td><?php echo $salesman['mobile']; ?></td>
			<td><?php echo $salesman['gender']; ?></td>
			<td><?php echo $salesman['status']; ?></td>
			<td><?php echo $salesman['company']; ?></td>
			<td><?php echo $salesman['country']; ?></td>
			<td><?php echo $salesman['created_at']; ?></td>
			<td><?php echo $salesman['updated_at']; ?></td>
			<td><a href="index.php?c=salesman&a=salesman_price_grid&id=<?php echo $salesman['salesman_id']; ?>">prices</td>
			<td><a href="index.php?c=salesman&a=edit&id=<?php echo $salesman['salesman_id']; ?>">Edit</td>
			<td><a href="index.php?c=salesman&a=delete&id=<?php echo $salesman['salesman_id']; ?>">Delete</td>
		</tr>

	<?php endforeach; ?>
</table>
</div>
<?php require_once 'View\html\footer.phtml' ?>
</form>
</body>
</html>