<!--ADD PRODUCT-->
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Add Shipping Method</title>
</head>
<body>
<form action="index.php?c=ShippingMethod&a=insert" method="post">
<?php require_once 'View\html\header.phtml' ?>
<div class="content">
<br>
<table class="tc">
	<tr>
		<td class="heading"> ADD SHIPPING METHOD</td>
		<td>
			<a href="index.php?c=ShippingMethod&a=grid">Cancel </a>
		</td>
		<td>
			<input type="submit" name="button" value="ADD">
		</td>
	</tr>
</table>
<br>
<table border="1" cellspacing="0"  class="tc">
	<tr>
		<th colspan="2"><strong>Shipping method Information</strong></th>
	</tr>
	<tr>
		<td class="tth">Name</td>
		<td>
			<input type="text" name="shipping_method[name]" placeholder="name">
		</td>
	</tr>
	<tr>
		<td class="tth">Amount</td>
		<td>
			<input type="number" name="shipping_method[amount]" placeholder="Amount">
		</td>
	</tr>
	<tr>
		<td class="tth">Status</td>
		<td>
			<select name="shipping_method[status]">
				<option>-Choose an Option-</option>
				<option value="active">Active</option>
				<option value="inactive">Inactive</option>
			</select>
		</td>
	</tr>
</table>
</div>
<?php require_once 'View\html\footer.phtml' ?>
</form>
</body>
</html>