<?php 
require_once 'Model\Core\Model_Adapter.php';

$result = new Model_Adapter();
$sql = "SELECT * FROM shipping_method";
$datas = $result->fetchAll($sql);

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<form action="index.php?c=ShippingMethod&a=add" method="post">
<?php require_once 'View\html\header.phtml' ?>
<div class="content">
<table class="tc">
	<tr>
		<td class="heading"> Shipping_Method</td>
		<td>
			<input type="submit" name="add" value="Add Shipping_Method">
		</td>
	</tr>
</table>
<br>
<table border="1" cellspacing="0" class="tc">
	<tr style="height: 30px; font-size: 18px;">
		<th>Shipping_Method ID</th>
		<th>Name</th>
		<th>Amount</th>
		<th>status</th>
		<th>Created At</th>
		<th>Updated At</th>
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>

	<?php foreach ($datas as $shipping_method): ?>

	<tr class="center">
		<td><?php echo $shipping_method['shipping_method_id']; ?></td>
		<td><?php echo $shipping_method['name']; ?></td>
		<td><?php echo $shipping_method['amount']; ?></td>
		<td><?php echo $shipping_method['status']; ?></td>
		<td><?php echo $shipping_method['created_at']; ?></td>
		<td><?php echo $shipping_method['updated_at']; ?></td>
		<td><a href="index.php?c=ShippingMethod&a=edit&id=<?php echo $shipping_method['shipping_method_id']; ?>">Edit</td>
		<td><a href="index.php?c=ShippingMethod&a=delete&id=<?php echo $shipping_method['shipping_method_id']; ?>">Delete</td>
	</tr>

	<?php endforeach; ?>
</table>
</div>
<?php require_once 'View\html\footer.phtml' ?>
</form>
</body>
</html>